version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workout_db
    ports:
      - "5432:5432"

  workout-api:
    build: 
      context: .
      dockerfile: dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/workout_db
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8000:8000"
    depends_on:
      - db